# Generated by Django 5.1.4 on 2025-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogify', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
